theme: jekyll-theme-cayman
title: Bienvenue sur le site du cours d'introduction au Machine Learning de PolyAI!
description: Toutes les ressources nécessaires pour le cours se retrouvera ici! Plan de cours, exercices, notes de cours, et plus encore!
